### ISSUE TITLE
gulp-autoprefixer css syntax error

### ISSUE THREAD

**Issue by jenniferhail** [zoerooney/yo-emi#20]
Running gulp watch throws an unknown word error in style.css.map:3:1

I read through this thread, https://github.com/sindresorhus/gulp-autoprefixer/issues/20, but I'm not sure of the fix.

**Comment by zoerooney** [comment]
A couple things to try:
* Make sure the gulpfile is the most recent version, same with the package.json file
* Make sure Gulp is up to date (and all packages in the theme - sometimes I just delete the whole node_packages file and reinstall after updating the package.json file)
* Run `gulp styles` to see if it's the watch task or something in the styles flow (sounds like the latter)

LMK how those go and then I'll check further!

**Comment by jenniferhail** [comment]
I ran yo emi which should have pulled the most recent files, so I think that part is good.
Just updated Gulp globally and locally. Tried deleting the node_packages file, but I can't figure out how to reinstall it in the theme folder.
Before I deleted `node_packages` I ran gulp styles and the same error occurred.

**Comment by zoerooney** [comment]
You can reinstall the packages by running `npm install`

I'm going to move this over to the Emi issues, since it's really an Emi issue, not a generator issue.

**Comment by zoerooney** [comment]
This issue was moved to zoerooney/Emi#35
